SET NOCOUNT ON;

/*
Validate Welcome "Delivery Baseline" KPI for a specific Program/Team scope.

Inputs:
  - @selected_year : same year selected in Welcome
  - @program_name  : program scope label (PROGRAMNAME)
  - @team_name     : team scope label (TEAMNAME)
  - @as_of_date    : usually today

This reproduces the source-chain logic used by Welcome:
  TEAM -> PROGRAM -> GLOBAL
for the selected reference PI (last closed PI; fallback to latest non-future PI).
*/

DECLARE @selected_year INT = 2026;
DECLARE @program_name NVARCHAR(200) = N'R&M';
DECLARE @team_name NVARCHAR(200) = N'ERNE WEST';
DECLARE @as_of_date DATE = CAST(GETDATE() AS DATE);

IF OBJECT_ID('tempdb..#picked_source') IS NOT NULL
  DROP TABLE #picked_source;

;WITH cal0 AS (
  SELECT
    TRY_CONVERT(INT, YEAR) AS CAL_YEAR,
    UPPER(LTRIM(RTRIM(ITERATION_LEVEL3))) AS CAL_L3,
    MIN(START_DATE) AS CAL_START_DATE,
    MAX(END_DATE) AS CAL_END_DATE
  FROM ADO_ITERATION_CALENDAR
  WHERE UPPER(COALESCE(ITERATION_GRAIN, 'PI')) = 'PI'
    AND TRY_CONVERT(INT, YEAR) = @selected_year
    AND ITERATION_LEVEL3 IS NOT NULL
  GROUP BY
    TRY_CONVERT(INT, YEAR),
    UPPER(LTRIM(RTRIM(ITERATION_LEVEL3)))
),
cal AS (
  SELECT
    CAL_YEAR,
    CASE
      WHEN PATINDEX('%PI[1-4]%', CAL_L3) > 0 THEN TRY_CONVERT(INT, SUBSTRING(CAL_L3, PATINDEX('%PI[1-4]%', CAL_L3) + 2, 1))
      WHEN PATINDEX('% I[1-4]%', CAL_L3) > 0 THEN TRY_CONVERT(INT, SUBSTRING(CAL_L3, PATINDEX('% I[1-4]%', CAL_L3) + 2, 1))
      WHEN PATINDEX('%I[1-4]%', CAL_L3) > 0 THEN TRY_CONVERT(INT, SUBSTRING(CAL_L3, PATINDEX('%I[1-4]%', CAL_L3) + 1, 1))
      ELSE NULL
    END AS PI_NUM,
    CAL_START_DATE,
    CAL_END_DATE,
    CAL_L3
  FROM cal0
),
cal2 AS (
  SELECT
    CAL_YEAR,
    PI_NUM,
    (CAL_YEAR * 100 + PI_NUM) AS PI_ORDER,
    CAL_START_DATE,
    CAL_END_DATE,
    CAL_L3
  FROM cal
  WHERE PI_NUM BETWEEN 1 AND 4
),
ref_pi AS (
  SELECT
    COALESCE(
      (
        SELECT TOP (1) PI_ORDER
        FROM cal2
        WHERE CAL_END_DATE < @as_of_date
        ORDER BY CAL_END_DATE DESC, PI_ORDER DESC
      ),
      (
        SELECT TOP (1) PI_ORDER
        FROM cal2
        WHERE CAL_START_DATE <= @as_of_date
        ORDER BY PI_ORDER DESC, CAL_START_DATE DESC
      )
    ) AS TARGET_PI_ORDER
),
v0 AS (
  SELECT
    UPPER(LTRIM(RTRIM(COALESCE(BASELINE_SOURCE, 'GLOBAL')))) AS BASELINE_SOURCE,
    UPPER(LTRIM(RTRIM(COALESCE(PROGRAMNAME, '')))) AS PROGRAM_U,
    UPPER(LTRIM(RTRIM(COALESCE(TEAMNAME, '')))) AS TEAM_U,
    TRY_CONVERT(INT, YEAR) AS YEAR_I,
    TRY_CONVERT(INT, PI) AS PI_I,
    TRY_CONVERT(INT, YEAR) * 100 + TRY_CONVERT(INT, PI) AS PI_ORDER,
    TRY_CONVERT(FLOAT, PI_POINTS_DONE) AS PI_POINTS_DONE,
    TRY_CONVERT(FLOAT, EFFECTIVE_BASELINE_POINTS) AS EFFECTIVE_BASELINE_POINTS,
    TRY_CONVERT(FLOAT, BASELINE_PREV) AS BASELINE_PREV,
    TRY_CONVERT(INT, BASELINE_CHANGED_FLAG) AS BASELINE_CHANGED_FLAG,
    PROGRAMNAME,
    TEAMNAME,
    PI_LABEL
  FROM TCO_TEAM_VELOCITY_SNAPSHOT
  WHERE TRY_CONVERT(INT, YEAR) BETWEEN (@selected_year - 1) AND @selected_year
),
v_scope AS (
  SELECT *
  FROM v0
  WHERE
    (BASELINE_SOURCE = 'TEAM' AND TEAM_U = UPPER(LTRIM(RTRIM(@team_name))))
    OR (BASELINE_SOURCE = 'PROGRAM' AND PROGRAM_U = UPPER(LTRIM(RTRIM(@program_name))))
    OR (BASELINE_SOURCE = 'GLOBAL')
),
target AS (
  SELECT COALESCE(
      (SELECT TARGET_PI_ORDER FROM ref_pi),
      (SELECT MAX(PI_ORDER) FROM v_scope)
    ) AS TARGET_PI_ORDER
),
order_rank AS (
  SELECT
    PI_ORDER,
    MIN(
      CASE
        WHEN BASELINE_SOURCE = 'TEAM' AND TEAM_U = UPPER(LTRIM(RTRIM(@team_name))) THEN 1
        WHEN BASELINE_SOURCE = 'PROGRAM' AND PROGRAM_U = UPPER(LTRIM(RTRIM(@program_name))) THEN 2
        WHEN BASELINE_SOURCE = 'GLOBAL' THEN 3
        ELSE 99
      END
    ) AS BEST_RANK
  FROM v_scope
  WHERE PI_ORDER IS NOT NULL
  GROUP BY PI_ORDER
),
chosen_order AS (
  SELECT TOP (1)
    r.PI_ORDER,
    r.BEST_RANK
  FROM order_rank r
  CROSS JOIN target t
  WHERE r.BEST_RANK < 99
    AND r.PI_ORDER <= t.TARGET_PI_ORDER
  ORDER BY r.PI_ORDER DESC
),
picked AS (
  SELECT
    s.*,
    c.BEST_RANK,
    CASE
      WHEN s.BASELINE_SOURCE = 'TEAM' AND s.TEAM_U = UPPER(LTRIM(RTRIM(@team_name))) THEN 1
      WHEN s.BASELINE_SOURCE = 'PROGRAM' AND s.PROGRAM_U = UPPER(LTRIM(RTRIM(@program_name))) THEN 2
      WHEN s.BASELINE_SOURCE = 'GLOBAL' THEN 3
      ELSE 99
    END AS SRC_RANK
  FROM v_scope s
  JOIN chosen_order c
    ON c.PI_ORDER = s.PI_ORDER
),
picked_source AS (
  SELECT *
  FROM picked
  WHERE SRC_RANK = BEST_RANK
)
SELECT
  ps.*,
  t.TARGET_PI_ORDER,
  c.PI_ORDER AS CHOSEN_PI_ORDER,
  c.BEST_RANK AS CHOSEN_SOURCE_RANK
INTO #picked_source
FROM picked_source ps
CROSS JOIN target t
CROSS JOIN chosen_order c;

;WITH agg AS (
  SELECT
    COUNT(*) AS ROWS_N,
    SUM(CASE WHEN COALESCE(PI_POINTS_DONE, 0) > 0 THEN PI_POINTS_DONE ELSE 0 END) AS W_SUM,
    SUM(CASE WHEN COALESCE(PI_POINTS_DONE, 0) > 0 THEN PI_POINTS_DONE * COALESCE(EFFECTIVE_BASELINE_POINTS, 0) ELSE 0 END) AS WX_SUM,
    AVG(EFFECTIVE_BASELINE_POINTS) AS AVG_BASELINE
  FROM #picked_source
),
meta AS (
  SELECT
    MAX(TARGET_PI_ORDER) AS TARGET_PI_ORDER,
    MAX(CHOSEN_PI_ORDER) AS CHOSEN_PI_ORDER,
    MAX(CHOSEN_SOURCE_RANK) AS CHOSEN_SOURCE_RANK
  FROM #picked_source
)
SELECT
  @selected_year AS SELECTED_YEAR,
  @program_name AS PROGRAM_SCOPE,
  @team_name AS TEAM_SCOPE,
  @as_of_date AS AS_OF_DATE,
  m.TARGET_PI_ORDER,
  m.CHOSEN_PI_ORDER,
  m.CHOSEN_SOURCE_RANK,
  CASE m.CHOSEN_SOURCE_RANK
    WHEN 1 THEN 'TEAM'
    WHEN 2 THEN 'PROGRAM'
    WHEN 3 THEN 'GLOBAL'
    ELSE 'NONE'
  END AS CHOSEN_SOURCE,
  CASE
    WHEN COALESCE(a.W_SUM, 0) > 0 THEN a.WX_SUM / NULLIF(a.W_SUM, 0)
    ELSE a.AVG_BASELINE
  END AS DELIVERY_BASELINE_POINTS_PER_PI,
  a.ROWS_N AS ROWS_USED
FROM agg a
CROSS JOIN meta m;

-- Rows used for the KPI calculation (audit trail).
SELECT
  PI_LABEL,
  YEAR_I AS YEAR,
  PI_I AS PI,
  PROGRAMNAME,
  TEAMNAME,
  BASELINE_SOURCE,
  PI_POINTS_DONE,
  EFFECTIVE_BASELINE_POINTS,
  BASELINE_PREV,
  BASELINE_CHANGED_FLAG
FROM #picked_source
ORDER BY TEAMNAME, PROGRAMNAME;

-- Optional: feature-level sanity check for inverse relation
-- (higher EFFECTIVE_BASELINE_POINTS => lower DERIVED_FTE_FEATURE_VELOCITY for same SWAG_POINTS).
SELECT TOP (30)
  FEATURE_ID,
  TRY_CONVERT(INT, YEAR) AS YEAR,
  TRY_CONVERT(INT, PI) AS PI,
  TEAMNAME,
  PROGRAMNAME,
  TRY_CONVERT(FLOAT, SWAG_POINTS) AS SWAG_POINTS,
  TRY_CONVERT(FLOAT, EFFECTIVE_BASELINE_POINTS) AS EFFECTIVE_BASELINE_POINTS,
  TRY_CONVERT(FLOAT, DERIVED_FTE_FEATURE) AS DERIVED_FTE_SWAG,
  TRY_CONVERT(FLOAT, DERIVED_FTE_FEATURE_VELOCITY) AS DERIVED_FTE_VELOCITY,
  CASE
    WHEN TRY_CONVERT(FLOAT, EFFECTIVE_BASELINE_POINTS) > 0
      THEN TRY_CONVERT(FLOAT, SWAG_POINTS) / TRY_CONVERT(FLOAT, EFFECTIVE_BASELINE_POINTS)
    ELSE NULL
  END AS EXPECTED_DERIVED_FTE_VELOCITY
FROM VW_TCO_FEATURE_DEMAND
WHERE UPPER(LTRIM(RTRIM(COALESCE(PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name)))
  AND UPPER(LTRIM(RTRIM(COALESCE(TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name)))
  AND TRY_CONVERT(INT, YEAR) IN (@selected_year, @selected_year - 1)
  AND COALESCE(IN_SCOPE_FOR_ROADMAP, 0) = 1
ORDER BY TRY_CONVERT(INT, YEAR) DESC, TRY_CONVERT(INT, PI) DESC, FEATURE_ID;
