SET NOCOUNT ON;

/*
P4.0 - Model fidelity overview

Purpose:
- Quantify how much projected demand can be explained by velocity snapshot coverage.
- Show baseline source mix and effective baseline point distribution.

Inputs:
  @year_from / @year_to
*/

DECLARE @year_from INT = 2025;
DECLARE @year_to INT = 2026;

IF @year_from > @year_to
BEGIN
  DECLARE @tmp_year INT = @year_from;
  SET @year_from = @year_to;
  SET @year_to = @tmp_year;
END;

;WITH demand AS (
  SELECT
    COALESCE(NULLIF(LTRIM(RTRIM(d.TEAMID)), ''), 'UNKNOWN') AS TEAMID,
    TRY_CONVERT(INT, d.YEAR) AS YEAR_I,
    TRY_CONVERT(INT, d.PI) AS PI_I,
    TRY_CONVERT(FLOAT, d.SWAG_POINTS) AS SWAG_POINTS,
    TRY_CONVERT(FLOAT, d.DERIVED_FTE_FEATURE) AS DERIVED_FTE_SWAG
  FROM VW_TCO_FEATURE_DEMAND d
  WHERE TRY_CONVERT(INT, d.YEAR) BETWEEN @year_from AND @year_to
    AND TRY_CONVERT(INT, d.PI) IS NOT NULL
    AND COALESCE(d.IN_SCOPE_FOR_ROADMAP, 0) = 1
    AND COALESCE(d.IS_MSP_FEATURE, 0) = 0
),
snap AS (
  SELECT DISTINCT
    COALESCE(NULLIF(LTRIM(RTRIM(v.TEAMID)), ''), 'UNKNOWN') AS TEAMID,
    TRY_CONVERT(INT, v.YEAR) AS YEAR_I,
    TRY_CONVERT(INT, v.PI) AS PI_I
  FROM TCO_TEAM_VELOCITY_SNAPSHOT v
  WHERE TRY_CONVERT(INT, v.YEAR) BETWEEN @year_from AND @year_to
    AND TRY_CONVERT(INT, v.PI) IS NOT NULL
    AND COALESCE(TRY_CONVERT(FLOAT, v.EFFECTIVE_BASELINE_POINTS), 0.0) > 0
),
joined AS (
  SELECT
    d.*,
    CASE WHEN s.TEAMID IS NOT NULL THEN 1 ELSE 0 END AS HAS_SNAPSHOT
  FROM demand d
  LEFT JOIN snap s
    ON s.TEAMID = d.TEAMID
   AND s.YEAR_I = d.YEAR_I
   AND s.PI_I = d.PI_I
)
SELECT
  @year_from AS YEAR_FROM,
  @year_to AS YEAR_TO,
  COUNT(*) AS DEMAND_ROWS,
  SUM(HAS_SNAPSHOT) AS DEMAND_ROWS_WITH_SNAPSHOT,
  SUM(CASE WHEN HAS_SNAPSHOT = 0 THEN 1 ELSE 0 END) AS DEMAND_ROWS_WITHOUT_SNAPSHOT,
  CAST(100.0 * SUM(HAS_SNAPSHOT) / NULLIF(COUNT(*), 0) AS DECIMAL(6,2)) AS SNAPSHOT_COVERAGE_PCT,
  CAST(SUM(COALESCE(SWAG_POINTS, 0.0)) AS DECIMAL(18,2)) AS SWAG_POINTS_SUM,
  CAST(SUM(COALESCE(DERIVED_FTE_SWAG, 0.0)) AS DECIMAL(18,2)) AS DERIVED_FTE_SWAG_SUM
FROM joined;

-- Snapshot baseline source mix (TEAM / PROGRAM / GLOBAL) in requested window.
SELECT
  UPPER(COALESCE(v.BASELINE_SOURCE, 'GLOBAL')) AS BASELINE_SOURCE,
  COUNT(*) AS ROWS_N,
  CAST(AVG(COALESCE(TRY_CONVERT(FLOAT, v.EFFECTIVE_BASELINE_POINTS), 0.0)) AS DECIMAL(18,2)) AS AVG_EFFECTIVE_BASELINE_POINTS,
  CAST(MIN(COALESCE(TRY_CONVERT(FLOAT, v.EFFECTIVE_BASELINE_POINTS), 0.0)) AS DECIMAL(18,2)) AS MIN_EFFECTIVE_BASELINE_POINTS,
  CAST(MAX(COALESCE(TRY_CONVERT(FLOAT, v.EFFECTIVE_BASELINE_POINTS), 0.0)) AS DECIMAL(18,2)) AS MAX_EFFECTIVE_BASELINE_POINTS
FROM TCO_TEAM_VELOCITY_SNAPSHOT v
WHERE TRY_CONVERT(INT, v.YEAR) BETWEEN @year_from AND @year_to
GROUP BY UPPER(COALESCE(v.BASELINE_SOURCE, 'GLOBAL'))
ORDER BY ROWS_N DESC;

-- Effective baseline point distribution (to detect concentration at 65/95).
SELECT
  CAST(COALESCE(TRY_CONVERT(FLOAT, v.EFFECTIVE_BASELINE_POINTS), 0.0) AS DECIMAL(18,2)) AS EFFECTIVE_BASELINE_POINTS,
  COUNT(*) AS ROWS_N
FROM TCO_TEAM_VELOCITY_SNAPSHOT v
WHERE TRY_CONVERT(INT, v.YEAR) BETWEEN @year_from AND @year_to
GROUP BY CAST(COALESCE(TRY_CONVERT(FLOAT, v.EFFECTIVE_BASELINE_POINTS), 0.0) AS DECIMAL(18,2))
ORDER BY ROWS_N DESC, EFFECTIVE_BASELINE_POINTS;
