SET NOCOUNT ON;

/*
P4.2 (fast) - Team calibration diagnostics via snapshots only

Why this script:
- Avoids heavy scans on VW_TCO_FEATURE_DEMAND in environments under DB pressure.
- Uses snapshot tables only:
  * TCO_PROJECTED_DEMAND_SNAPSHOT (SWAG_POINTS_SUM, DERIVED_FTE_SUM)
  * TCO_TEAM_VELOCITY_SNAPSHOT (EFFECTIVE_BASELINE_POINTS, BASELINE_SOURCE)

What this validates:
- Delivery baseline behavior by PI (65/95/etc).
- SWAG-derived FTE vs velocity-derived FTE from snapshot baseline:
    DERIVED_FTE_VELOCITY = SWAG_POINTS_SUM / EFFECTIVE_BASELINE_POINTS
- Expected inverse relation:
    if baseline points increase, derived FTE (for same SWAG) decreases.

Recommended first run:
  @year_from = 2025
  @year_to   = 2026
  @program_name = N'R&M'
  @team_name    = N'ERNE WEST'
*/

DECLARE @year_from INT = 2025;
DECLARE @year_to INT = 2026;
DECLARE @program_name NVARCHAR(200) = N'R&M';
DECLARE @team_name NVARCHAR(200) = N'ERNE WEST';

DECLARE @program_id_resolved NVARCHAR(200) = NULL;
DECLARE @team_id_resolved NVARCHAR(200) = NULL;
DECLARE @program_name_resolved NVARCHAR(200) = @program_name;
DECLARE @team_name_resolved NVARCHAR(200) = @team_name;

IF @year_from > @year_to
BEGIN
  DECLARE @tmp_year INT = @year_from;
  SET @year_from = @year_to;
  SET @year_to = @tmp_year;
END;

;WITH p_pick AS (
  SELECT TOP (1)
    NULLIF(LTRIM(RTRIM(p.PROGRAMID)), '') AS PROGRAMID_CANONICAL,
    NULLIF(LTRIM(RTRIM(p.PROGRAMNAME)), '') AS PROGRAMNAME_CANONICAL
  FROM PROGRAMS p
  WHERE UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name)))
     OR UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@program_name)))
  ORDER BY
    CASE
      WHEN UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@program_name))) THEN 0
      WHEN UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name))) THEN 1
      ELSE 2
    END
),
t_pick AS (
  SELECT TOP (1)
    NULLIF(LTRIM(RTRIM(t.TEAMID)), '') AS TEAMID_CANONICAL,
    NULLIF(LTRIM(RTRIM(t.TEAMNAME)), '') AS TEAMNAME_CANONICAL
  FROM TEAMS t
  WHERE UPPER(LTRIM(RTRIM(COALESCE(t.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name)))
     OR UPPER(LTRIM(RTRIM(COALESCE(t.TEAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@team_name)))
  ORDER BY
    CASE
      WHEN UPPER(LTRIM(RTRIM(COALESCE(t.TEAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@team_name))) THEN 0
      WHEN UPPER(LTRIM(RTRIM(COALESCE(t.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name))) THEN 1
      ELSE 2
    END
)
SELECT
  @program_id_resolved = (SELECT PROGRAMID_CANONICAL FROM p_pick),
  @program_name_resolved = COALESCE((SELECT PROGRAMNAME_CANONICAL FROM p_pick), @program_name),
  @team_id_resolved = (SELECT TEAMID_CANONICAL FROM t_pick),
  @team_name_resolved = COALESCE((SELECT TEAMNAME_CANONICAL FROM t_pick), @team_name);

IF OBJECT_ID('tempdb..#team_demand_pi') IS NOT NULL DROP TABLE #team_demand_pi;
IF OBJECT_ID('tempdb..#team_baseline_pi') IS NOT NULL DROP TABLE #team_baseline_pi;
IF OBJECT_ID('tempdb..#team_pi_join') IS NOT NULL DROP TABLE #team_pi_join;

SELECT
  TRY_CONVERT(INT, d.YEAR) AS YEAR_I,
  TRY_CONVERT(INT, d.PI) AS PI_I,
  SUM(COALESCE(TRY_CONVERT(FLOAT, d.SWAG_POINTS_SUM), 0.0)) AS SWAG_POINTS_SUM,
  SUM(COALESCE(TRY_CONVERT(FLOAT, d.DERIVED_FTE_SUM), 0.0)) AS DERIVED_FTE_SWAG_SUM,
  SUM(COALESCE(TRY_CONVERT(BIGINT, d.FEATURE_ROWS), 0)) AS FEATURE_ROWS
INTO #team_demand_pi
FROM TCO_PROJECTED_DEMAND_SNAPSHOT d
WHERE TRY_CONVERT(INT, d.YEAR) BETWEEN @year_from AND @year_to
  AND (
    (@program_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.PROGRAMID, '')))) = UPPER(LTRIM(RTRIM(@program_id_resolved))))
    OR (@program_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name_resolved))))
  )
  AND (
    (@team_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.TEAMID, '')))) = UPPER(LTRIM(RTRIM(@team_id_resolved))))
    OR (@team_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name_resolved))))
  )
GROUP BY TRY_CONVERT(INT, d.YEAR), TRY_CONVERT(INT, d.PI);

SELECT
  TRY_CONVERT(INT, s.YEAR) AS YEAR_I,
  TRY_CONVERT(INT, s.PI) AS PI_I,
  COALESCE(NULLIF(LTRIM(RTRIM(s.PI_LABEL)), ''), CONCAT(TRY_CONVERT(INT, s.YEAR), ' I', TRY_CONVERT(INT, s.PI))) AS PI_LABEL,
  UPPER(COALESCE(s.BASELINE_SOURCE, 'GLOBAL')) AS BASELINE_SOURCE,
  TRY_CONVERT(FLOAT, s.EFFECTIVE_BASELINE_POINTS) AS EFFECTIVE_BASELINE_POINTS,
  TRY_CONVERT(FLOAT, s.PI_POINTS_DONE) AS PI_POINTS_DONE
INTO #team_baseline_pi
FROM TCO_TEAM_VELOCITY_SNAPSHOT s
WHERE TRY_CONVERT(INT, s.YEAR) BETWEEN @year_from AND @year_to
  AND TRY_CONVERT(INT, s.PI) IS NOT NULL
  AND (
    (@program_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.PROGRAMID, '')))) = UPPER(LTRIM(RTRIM(@program_id_resolved))))
    OR (@program_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name_resolved))))
  )
  AND (
    (@team_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.TEAMID, '')))) = UPPER(LTRIM(RTRIM(@team_id_resolved))))
    OR (@team_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name_resolved))))
  );

SELECT
  COALESCE(d.YEAR_I, s.YEAR_I) AS YEAR_I,
  COALESCE(d.PI_I, s.PI_I) AS PI_I,
  COALESCE(s.PI_LABEL, CONCAT(COALESCE(d.YEAR_I, s.YEAR_I), ' I', COALESCE(d.PI_I, s.PI_I))) AS PI_LABEL,
  d.FEATURE_ROWS,
  d.SWAG_POINTS_SUM,
  d.DERIVED_FTE_SWAG_SUM,
  s.BASELINE_SOURCE,
  s.EFFECTIVE_BASELINE_POINTS,
  s.PI_POINTS_DONE,
  CASE
    WHEN COALESCE(s.EFFECTIVE_BASELINE_POINTS, 0.0) > 0
      THEN COALESCE(d.SWAG_POINTS_SUM, 0.0) / NULLIF(s.EFFECTIVE_BASELINE_POINTS, 0.0)
    ELSE NULL
  END AS DERIVED_FTE_VELOCITY_SNAPSHOT
INTO #team_pi_join
FROM #team_demand_pi d
FULL OUTER JOIN #team_baseline_pi s
  ON s.YEAR_I = d.YEAR_I
 AND s.PI_I = d.PI_I;

-- Resultset 1: summary for requested scope/window.
SELECT
  @year_from AS YEAR_FROM,
  @year_to AS YEAR_TO,
  @program_name_resolved AS PROGRAM_SCOPE,
  @team_name_resolved AS TEAM_SCOPE,
  COUNT(*) AS PI_ROWS_IN_SCOPE,
  SUM(COALESCE(FEATURE_ROWS, 0)) AS FEATURE_ROWS_IN_SCOPE,
  CAST(SUM(COALESCE(SWAG_POINTS_SUM, 0.0)) AS DECIMAL(18,2)) AS SWAG_POINTS_TOTAL,
  CAST(SUM(COALESCE(DERIVED_FTE_SWAG_SUM, 0.0)) AS DECIMAL(18,2)) AS DERIVED_FTE_SWAG_TOTAL,
  CAST(SUM(COALESCE(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0)) AS DECIMAL(18,2)) AS DERIVED_FTE_VELOCITY_SNAPSHOT_TOTAL,
  CAST(
    SUM(COALESCE(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0))
    - SUM(COALESCE(DERIVED_FTE_SWAG_SUM, 0.0))
    AS DECIMAL(18,2)
  ) AS DELTA_VELOCITY_MINUS_SWAG,
  COUNT(DISTINCT CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2))) AS DISTINCT_BASELINE_VALUES,
  CAST(MIN(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0)) AS DECIMAL(18,2)) AS MIN_BASELINE_POINTS,
  CAST(MAX(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0)) AS DECIMAL(18,2)) AS MAX_BASELINE_POINTS
FROM #team_pi_join;

-- Resultset 2: PI-level calibration view.
SELECT
  YEAR_I AS YEAR,
  PI_I AS PI,
  PI_LABEL,
  COALESCE(BASELINE_SOURCE, 'GLOBAL') AS BASELINE_SOURCE,
  CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2)) AS EFFECTIVE_BASELINE_POINTS,
  CAST(COALESCE(PI_POINTS_DONE, 0.0) AS DECIMAL(18,2)) AS PI_POINTS_DONE,
  COALESCE(FEATURE_ROWS, 0) AS FEATURE_ROWS,
  CAST(COALESCE(SWAG_POINTS_SUM, 0.0) AS DECIMAL(18,2)) AS SWAG_POINTS_SUM,
  CAST(COALESCE(DERIVED_FTE_SWAG_SUM, 0.0) AS DECIMAL(18,3)) AS DERIVED_FTE_SWAG_SUM,
  CAST(COALESCE(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0) AS DECIMAL(18,3)) AS DERIVED_FTE_VELOCITY_SNAPSHOT,
  CAST(
    COALESCE(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0)
    - COALESCE(DERIVED_FTE_SWAG_SUM, 0.0)
    AS DECIMAL(18,3)
  ) AS DELTA_V_MINUS_SWAG,
  CAST(
    CASE
      WHEN COALESCE(DERIVED_FTE_SWAG_SUM, 0.0) > 0
        THEN COALESCE(SWAG_POINTS_SUM, 0.0) / NULLIF(DERIVED_FTE_SWAG_SUM, 0.0)
      ELSE NULL
    END AS DECIMAL(18,2)
  ) AS IMPLIED_POINTS_PER_FTE_SWAG,
  CAST(
    CASE
      WHEN COALESCE(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0) > 0
        THEN COALESCE(SWAG_POINTS_SUM, 0.0) / NULLIF(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0)
      ELSE NULL
    END AS DECIMAL(18,2)
  ) AS IMPLIED_POINTS_PER_FTE_VELOCITY
FROM #team_pi_join
ORDER BY YEAR_I, PI_I;

-- Resultset 3: baseline concentration for team.
SELECT
  CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2)) AS BASELINE_POINTS,
  COALESCE(BASELINE_SOURCE, 'GLOBAL') AS BASELINE_SOURCE,
  COUNT(*) AS PI_ROWS_N,
  CAST(SUM(COALESCE(PI_POINTS_DONE, 0.0)) AS DECIMAL(18,2)) AS PI_POINTS_DONE_SUM
FROM #team_baseline_pi
GROUP BY
  CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2)),
  COALESCE(BASELINE_SOURCE, 'GLOBAL')
ORDER BY PI_ROWS_N DESC, BASELINE_POINTS;

