SET NOCOUNT ON;

/*
P4.2 - Team calibration diagnostics (historical)

Purpose:
- Validate whether baseline concentration (for example 65/95) is expected or indicates low variability.
- Benchmark one known team across historical PIs and compare:
  * SWAG-derived FTE totals
  * Velocity-derived FTE totals (view output)
  * Snapshot baseline points used per PI

Recommended first run:
  @year_from = 2025
  @year_to   = 2025
  @program_name = N'R&M'
  @team_name    = N'ERNE WEST'
*/

DECLARE @year_from INT = 2025;
DECLARE @year_to INT = 2025;
DECLARE @program_name NVARCHAR(200) = N'R&M';
DECLARE @team_name NVARCHAR(200) = N'ERNE WEST';
DECLARE @program_name_resolved NVARCHAR(200) = @program_name;
DECLARE @team_name_resolved NVARCHAR(200) = @team_name;
DECLARE @program_id_resolved NVARCHAR(200) = NULL;
DECLARE @team_id_resolved NVARCHAR(200) = NULL;

IF @year_from > @year_to
BEGIN
  DECLARE @tmp_year INT = @year_from;
  SET @year_from = @year_to;
  SET @year_to = @tmp_year;
END;

;WITH p_pick AS (
  SELECT TOP (1)
    NULLIF(LTRIM(RTRIM(p.PROGRAMID)), '') AS PROGRAMID_CANONICAL,
    NULLIF(LTRIM(RTRIM(p.PROGRAMNAME)), '') AS PROGRAMNAME_CANONICAL
  FROM PROGRAMS p
  WHERE UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name)))
     OR UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@program_name)))
  ORDER BY
    CASE
      WHEN UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@program_name))) THEN 0
      WHEN UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name))) THEN 1
      ELSE 2
    END
),
t_pick AS (
  SELECT TOP (1)
    NULLIF(LTRIM(RTRIM(t.TEAMID)), '') AS TEAMID_CANONICAL,
    NULLIF(LTRIM(RTRIM(t.TEAMNAME)), '') AS TEAMNAME_CANONICAL
  FROM TEAMS t
  WHERE UPPER(LTRIM(RTRIM(COALESCE(t.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name)))
     OR UPPER(LTRIM(RTRIM(COALESCE(t.TEAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@team_name)))
  ORDER BY
    CASE
      WHEN UPPER(LTRIM(RTRIM(COALESCE(t.TEAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@team_name))) THEN 0
      WHEN UPPER(LTRIM(RTRIM(COALESCE(t.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name))) THEN 1
      ELSE 2
    END
)
SELECT
  @program_id_resolved = (SELECT PROGRAMID_CANONICAL FROM p_pick),
  @program_name_resolved = COALESCE((SELECT PROGRAMNAME_CANONICAL FROM p_pick), @program_name),
  @team_id_resolved = (SELECT TEAMID_CANONICAL FROM t_pick),
  @team_name_resolved = COALESCE((SELECT TEAMNAME_CANONICAL FROM t_pick), @team_name);

IF OBJECT_ID('tempdb..#team_snapshot') IS NOT NULL
  DROP TABLE #team_snapshot;

IF OBJECT_ID('tempdb..#team_demand_pi') IS NOT NULL
  DROP TABLE #team_demand_pi;

IF OBJECT_ID('tempdb..#team_pi_join') IS NOT NULL
  DROP TABLE #team_pi_join;

SELECT
  TRY_CONVERT(INT, s.YEAR) AS YEAR_I,
  TRY_CONVERT(INT, s.PI) AS PI_I,
  COALESCE(NULLIF(LTRIM(RTRIM(s.PI_LABEL)), ''), CONCAT(TRY_CONVERT(INT, s.YEAR), ' I', TRY_CONVERT(INT, s.PI))) AS PI_LABEL,
  UPPER(COALESCE(s.BASELINE_SOURCE, 'GLOBAL')) AS BASELINE_SOURCE,
  TRY_CONVERT(FLOAT, s.EFFECTIVE_BASELINE_POINTS) AS EFFECTIVE_BASELINE_POINTS,
  TRY_CONVERT(FLOAT, s.PI_POINTS_DONE) AS PI_POINTS_DONE,
  TRY_CONVERT(INT, s.SAMPLE_PIS) AS SAMPLE_PIS
INTO #team_snapshot
FROM TCO_TEAM_VELOCITY_SNAPSHOT s
WHERE TRY_CONVERT(INT, s.YEAR) BETWEEN @year_from AND @year_to
  AND TRY_CONVERT(INT, s.PI) IS NOT NULL
  AND (
    (@program_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.PROGRAMID, '')))) = UPPER(LTRIM(RTRIM(@program_id_resolved))))
    OR (@program_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name_resolved))))
  )
  AND (
    (@team_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.TEAMID, '')))) = UPPER(LTRIM(RTRIM(@team_id_resolved))))
    OR (@team_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name_resolved))))
  );

SELECT
  TRY_CONVERT(INT, d.YEAR) AS YEAR_I,
  TRY_CONVERT(INT, d.PI) AS PI_I,
  COALESCE(NULLIF(LTRIM(RTRIM(MAX(d.PI_LABEL))), ''), CONCAT(TRY_CONVERT(INT, d.YEAR), ' I', TRY_CONVERT(INT, d.PI))) AS PI_LABEL,
  COUNT(DISTINCT d.FEATURE_ID) AS FEATURES_N,
  CAST(SUM(COALESCE(TRY_CONVERT(FLOAT, d.SWAG_POINTS), 0.0)) AS FLOAT) AS SWAG_POINTS_TOTAL,
  CAST(SUM(COALESCE(TRY_CONVERT(FLOAT, d.DERIVED_FTE_FEATURE), 0.0)) AS FLOAT) AS DERIVED_FTE_SWAG_TOTAL,
  CAST(SUM(COALESCE(TRY_CONVERT(FLOAT, d.DERIVED_FTE_FEATURE_VELOCITY), 0.0)) AS FLOAT) AS DERIVED_FTE_VELOCITY_VIEW_TOTAL
INTO #team_demand_pi
FROM VW_TCO_FEATURE_DEMAND d
WHERE TRY_CONVERT(INT, d.YEAR) BETWEEN @year_from AND @year_to
  AND TRY_CONVERT(INT, d.PI) IS NOT NULL
  AND COALESCE(d.IN_SCOPE_FOR_ROADMAP, 0) = 1
  AND COALESCE(TRY_CONVERT(INT, d.IS_MSP_FEATURE), 0) = 0
  AND (
    (@program_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.PROGRAMID, '')))) = UPPER(LTRIM(RTRIM(@program_id_resolved))))
    OR (@program_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name_resolved))))
  )
  AND (
    (@team_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.TEAMID, '')))) = UPPER(LTRIM(RTRIM(@team_id_resolved))))
    OR (@team_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(d.TEAMNAME, '')))) = UPPER(LTRIM(RTRIM(@team_name_resolved))))
  )
GROUP BY TRY_CONVERT(INT, d.YEAR), TRY_CONVERT(INT, d.PI);

SELECT
  COALESCE(dp.YEAR_I, sp.YEAR_I) AS YEAR_I,
  COALESCE(dp.PI_I, sp.PI_I) AS PI_I,
  COALESCE(dp.PI_LABEL, sp.PI_LABEL) AS PI_LABEL,
  dp.FEATURES_N,
  dp.SWAG_POINTS_TOTAL,
  dp.DERIVED_FTE_SWAG_TOTAL,
  dp.DERIVED_FTE_VELOCITY_VIEW_TOTAL,
  sp.BASELINE_SOURCE,
  sp.EFFECTIVE_BASELINE_POINTS,
  sp.PI_POINTS_DONE,
  sp.SAMPLE_PIS
INTO #team_pi_join
FROM #team_demand_pi dp
FULL OUTER JOIN #team_snapshot sp
  ON sp.YEAR_I = dp.YEAR_I
 AND sp.PI_I = dp.PI_I;

-- Resultset 1: team historical summary for the requested scope.
SELECT
  @year_from AS YEAR_FROM,
  @year_to AS YEAR_TO,
  @program_name_resolved AS PROGRAM_SCOPE,
  @team_name_resolved AS TEAM_SCOPE,
  COUNT(*) AS PI_ROWS_IN_SCOPE,
  SUM(CASE WHEN COALESCE(EFFECTIVE_BASELINE_POINTS, 0) > 0 THEN 1 ELSE 0 END) AS PI_ROWS_WITH_BASELINE,
  COUNT(DISTINCT CASE WHEN COALESCE(EFFECTIVE_BASELINE_POINTS, 0) > 0 THEN CAST(EFFECTIVE_BASELINE_POINTS AS DECIMAL(18,2)) END) AS DISTINCT_BASELINE_VALUES,
  CAST(MIN(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0)) AS DECIMAL(18,2)) AS MIN_BASELINE_POINTS,
  CAST(MAX(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0)) AS DECIMAL(18,2)) AS MAX_BASELINE_POINTS,
  CAST(AVG(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0)) AS DECIMAL(18,2)) AS AVG_BASELINE_POINTS,
  CAST(
    CASE
      WHEN SUM(CASE WHEN COALESCE(PI_POINTS_DONE, 0.0) > 0 THEN PI_POINTS_DONE ELSE 0.0 END) > 0
        THEN SUM(CASE WHEN COALESCE(PI_POINTS_DONE, 0.0) > 0 THEN PI_POINTS_DONE * COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) ELSE 0.0 END)
             / NULLIF(SUM(CASE WHEN COALESCE(PI_POINTS_DONE, 0.0) > 0 THEN PI_POINTS_DONE ELSE 0.0 END), 0.0)
      ELSE NULL
    END AS DECIMAL(18,2)
  ) AS WEIGHTED_BASELINE_BY_DONE_POINTS,
  CAST(SUM(COALESCE(SWAG_POINTS_TOTAL, 0.0)) AS DECIMAL(18,2)) AS SWAG_POINTS_TOTAL,
  CAST(SUM(COALESCE(DERIVED_FTE_SWAG_TOTAL, 0.0)) AS DECIMAL(18,2)) AS DERIVED_FTE_SWAG_TOTAL,
  CAST(SUM(COALESCE(DERIVED_FTE_VELOCITY_VIEW_TOTAL, 0.0)) AS DECIMAL(18,2)) AS DERIVED_FTE_VELOCITY_TOTAL,
  CAST(
    SUM(COALESCE(DERIVED_FTE_VELOCITY_VIEW_TOTAL, 0.0))
    - SUM(COALESCE(DERIVED_FTE_SWAG_TOTAL, 0.0))
    AS DECIMAL(18,2)
  ) AS DELTA_VELOCITY_MINUS_SWAG
FROM #team_pi_join;

-- Resultset 2: PI-level behavior.
SELECT
  YEAR_I AS YEAR,
  PI_I AS PI,
  PI_LABEL,
  COALESCE(BASELINE_SOURCE, 'GLOBAL') AS BASELINE_SOURCE,
  CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2)) AS EFFECTIVE_BASELINE_POINTS,
  CAST(COALESCE(PI_POINTS_DONE, 0.0) AS DECIMAL(18,2)) AS PI_POINTS_DONE,
  FEATURES_N,
  CAST(COALESCE(SWAG_POINTS_TOTAL, 0.0) AS DECIMAL(18,2)) AS SWAG_POINTS_TOTAL,
  CAST(COALESCE(DERIVED_FTE_SWAG_TOTAL, 0.0) AS DECIMAL(18,3)) AS DERIVED_FTE_SWAG_TOTAL,
  CAST(COALESCE(DERIVED_FTE_VELOCITY_VIEW_TOTAL, 0.0) AS DECIMAL(18,3)) AS DERIVED_FTE_VELOCITY_TOTAL,
  CAST(
    CASE
      WHEN COALESCE(DERIVED_FTE_VELOCITY_VIEW_TOTAL, 0.0) > 0
        THEN COALESCE(SWAG_POINTS_TOTAL, 0.0) / NULLIF(DERIVED_FTE_VELOCITY_VIEW_TOTAL, 0.0)
      ELSE NULL
    END AS DECIMAL(18,2)
  ) AS IMPLIED_POINTS_PER_FTE_FROM_VELOCITY,
  CAST(
    CASE
      WHEN COALESCE(DERIVED_FTE_SWAG_TOTAL, 0.0) > 0
        THEN COALESCE(SWAG_POINTS_TOTAL, 0.0) / NULLIF(DERIVED_FTE_SWAG_TOTAL, 0.0)
      ELSE NULL
    END AS DECIMAL(18,2)
  ) AS IMPLIED_POINTS_PER_FTE_FROM_SWAG
FROM #team_pi_join
ORDER BY YEAR_I, PI_I;

-- Resultset 3: baseline value concentration for this team in the window.
SELECT
  CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2)) AS BASELINE_POINTS,
  COUNT(*) AS PI_ROWS_N,
  CAST(SUM(COALESCE(PI_POINTS_DONE, 0.0)) AS DECIMAL(18,2)) AS PI_POINTS_DONE_SUM
FROM #team_snapshot
GROUP BY CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2))
ORDER BY PI_ROWS_N DESC, BASELINE_POINTS;

-- Resultset 4: program-level baseline concentration for comparison context.
SELECT
  CAST(COALESCE(TRY_CONVERT(FLOAT, s.EFFECTIVE_BASELINE_POINTS), 0.0) AS DECIMAL(18,2)) AS BASELINE_POINTS,
  UPPER(COALESCE(s.BASELINE_SOURCE, 'GLOBAL')) AS BASELINE_SOURCE,
  COUNT(*) AS ROWS_N
FROM TCO_TEAM_VELOCITY_SNAPSHOT s
WHERE TRY_CONVERT(INT, s.YEAR) BETWEEN @year_from AND @year_to
  AND (
    (@program_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.PROGRAMID, '')))) = UPPER(LTRIM(RTRIM(@program_id_resolved))))
    OR (@program_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(s.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name_resolved))))
  )
GROUP BY
  CAST(COALESCE(TRY_CONVERT(FLOAT, s.EFFECTIVE_BASELINE_POINTS), 0.0) AS DECIMAL(18,2)),
  UPPER(COALESCE(s.BASELINE_SOURCE, 'GLOBAL'))
ORDER BY ROWS_N DESC, BASELINE_POINTS;
