SET NOCOUNT ON;

/*
P4.3 (fast) - Program-wide team fidelity ranking via snapshots

Purpose:
- Rank teams in one program by impact of velocity model vs SWAG model.
- Works on snapshot tables only (fast / low timeout risk):
  * TCO_PROJECTED_DEMAND_SNAPSHOT
  * TCO_TEAM_VELOCITY_SNAPSHOT

Primary metric:
  DELTA_VELOCITY_MINUS_SWAG = SUM( SWAG_POINTS_SUM / BASELINE_POINTS ) - SUM( DERIVED_FTE_SWAG_SUM )

Interpretation:
- Negative delta: velocity model reduces derived FTE vs SWAG-fixed path (expected when baseline > 65).
- Positive delta: velocity model increases derived FTE vs SWAG-fixed path (expected when baseline < 65).
*/

DECLARE @year_from INT = 2025;
DECLARE @year_to INT = 2026;
DECLARE @program_name NVARCHAR(200) = N'R&M';
DECLARE @exclude_seed_teams BIT = 1;
DECLARE @program_id_resolved NVARCHAR(200) = NULL;
DECLARE @program_name_resolved NVARCHAR(200) = @program_name;

IF @year_from > @year_to
BEGIN
  DECLARE @tmp_year INT = @year_from;
  SET @year_from = @year_to;
  SET @year_to = @tmp_year;
END;

;WITH p_pick AS (
  SELECT TOP (1)
    NULLIF(LTRIM(RTRIM(p.PROGRAMID)), '') AS PROGRAMID_CANONICAL,
    NULLIF(LTRIM(RTRIM(p.PROGRAMNAME)), '') AS PROGRAMNAME_CANONICAL
  FROM PROGRAMS p
  WHERE UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name)))
     OR UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@program_name)))
  ORDER BY
    CASE
      WHEN UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAM_DISPLAY_NAME, '')))) = UPPER(LTRIM(RTRIM(@program_name))) THEN 0
      WHEN UPPER(LTRIM(RTRIM(COALESCE(p.PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name))) THEN 1
      ELSE 2
    END
)
SELECT
  @program_id_resolved = (SELECT PROGRAMID_CANONICAL FROM p_pick),
  @program_name_resolved = COALESCE((SELECT PROGRAMNAME_CANONICAL FROM p_pick), @program_name);

;WITH d AS (
  SELECT
    COALESCE(NULLIF(LTRIM(RTRIM(TEAMID)), ''), 'UNKNOWN') AS TEAMID,
    COALESCE(NULLIF(LTRIM(RTRIM(TEAMNAME)), ''), '(Unassigned)') AS TEAMNAME,
    TRY_CONVERT(INT, YEAR) AS YEAR_I,
    TRY_CONVERT(INT, PI) AS PI_I,
    SUM(COALESCE(TRY_CONVERT(FLOAT, SWAG_POINTS_SUM), 0.0)) AS SWAG_POINTS_SUM,
    SUM(COALESCE(TRY_CONVERT(FLOAT, DERIVED_FTE_SUM), 0.0)) AS DERIVED_FTE_SWAG_SUM,
    SUM(COALESCE(TRY_CONVERT(BIGINT, FEATURE_ROWS), 0)) AS FEATURE_ROWS
  FROM TCO_PROJECTED_DEMAND_SNAPSHOT
  WHERE TRY_CONVERT(INT, YEAR) BETWEEN @year_from AND @year_to
    AND (
      (@program_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(PROGRAMID, '')))) = UPPER(LTRIM(RTRIM(@program_id_resolved))))
      OR (@program_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name_resolved))))
    )
    AND (
      @exclude_seed_teams = 0
      OR (
        UPPER(LTRIM(RTRIM(COALESCE(TEAMID, '')))) NOT LIKE 'MOIT_SEED_%'
        AND UPPER(LTRIM(RTRIM(COALESCE(TEAMNAME, '')))) NOT LIKE '[[]SEED]%'
      )
    )
  GROUP BY
    COALESCE(NULLIF(LTRIM(RTRIM(TEAMID)), ''), 'UNKNOWN'),
    COALESCE(NULLIF(LTRIM(RTRIM(TEAMNAME)), ''), '(Unassigned)'),
    TRY_CONVERT(INT, YEAR),
    TRY_CONVERT(INT, PI)
),
s AS (
  SELECT
    COALESCE(NULLIF(LTRIM(RTRIM(TEAMID)), ''), 'UNKNOWN') AS TEAMID,
    TRY_CONVERT(INT, YEAR) AS YEAR_I,
    TRY_CONVERT(INT, PI) AS PI_I,
    UPPER(COALESCE(BASELINE_SOURCE, 'GLOBAL')) AS BASELINE_SOURCE,
    TRY_CONVERT(FLOAT, EFFECTIVE_BASELINE_POINTS) AS EFFECTIVE_BASELINE_POINTS,
    TRY_CONVERT(FLOAT, PI_POINTS_DONE) AS PI_POINTS_DONE
  FROM TCO_TEAM_VELOCITY_SNAPSHOT
  WHERE TRY_CONVERT(INT, YEAR) BETWEEN @year_from AND @year_to
    AND TRY_CONVERT(INT, PI) IS NOT NULL
    AND (
      (@program_id_resolved IS NOT NULL AND UPPER(LTRIM(RTRIM(COALESCE(PROGRAMID, '')))) = UPPER(LTRIM(RTRIM(@program_id_resolved))))
      OR (@program_id_resolved IS NULL AND UPPER(LTRIM(RTRIM(COALESCE(PROGRAMNAME, '')))) = UPPER(LTRIM(RTRIM(@program_name_resolved))))
    )
    AND (
      @exclude_seed_teams = 0
      OR (
        UPPER(LTRIM(RTRIM(COALESCE(TEAMID, '')))) NOT LIKE 'MOIT_SEED_%'
        AND UPPER(LTRIM(RTRIM(COALESCE(TEAMNAME, '')))) NOT LIKE '[[]SEED]%'
      )
    )
),
j AS (
  SELECT
    d.TEAMID,
    d.TEAMNAME,
    d.YEAR_I,
    d.PI_I,
    d.FEATURE_ROWS,
    d.SWAG_POINTS_SUM,
    d.DERIVED_FTE_SWAG_SUM,
    s.BASELINE_SOURCE,
    s.EFFECTIVE_BASELINE_POINTS,
    s.PI_POINTS_DONE,
    CASE
      WHEN COALESCE(s.EFFECTIVE_BASELINE_POINTS, 0.0) > 0
        THEN COALESCE(d.SWAG_POINTS_SUM, 0.0) / NULLIF(s.EFFECTIVE_BASELINE_POINTS, 0.0)
      ELSE NULL
    END AS DERIVED_FTE_VELOCITY_SNAPSHOT
  FROM d
  LEFT JOIN s
    ON s.TEAMID = d.TEAMID
   AND s.YEAR_I = d.YEAR_I
   AND s.PI_I = d.PI_I
),
team_agg AS (
  SELECT
    TEAMID,
    TEAMNAME,
    COUNT(*) AS PI_ROWS,
    SUM(COALESCE(FEATURE_ROWS, 0)) AS FEATURE_ROWS,
    CAST(SUM(COALESCE(SWAG_POINTS_SUM, 0.0)) AS FLOAT) AS SWAG_POINTS_TOTAL,
    CAST(SUM(COALESCE(DERIVED_FTE_SWAG_SUM, 0.0)) AS FLOAT) AS DERIVED_FTE_SWAG_TOTAL,
    CAST(SUM(COALESCE(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0)) AS FLOAT) AS DERIVED_FTE_VELOCITY_SNAPSHOT_TOTAL,
    CAST(
      SUM(COALESCE(DERIVED_FTE_VELOCITY_SNAPSHOT, 0.0))
      - SUM(COALESCE(DERIVED_FTE_SWAG_SUM, 0.0))
      AS FLOAT
    ) AS DELTA_VELOCITY_MINUS_SWAG,
    COUNT(DISTINCT CAST(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0) AS DECIMAL(18,2))) AS DISTINCT_BASELINE_VALUES,
    CAST(MIN(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0)) AS FLOAT) AS MIN_BASELINE_POINTS,
    CAST(MAX(COALESCE(EFFECTIVE_BASELINE_POINTS, 0.0)) AS FLOAT) AS MAX_BASELINE_POINTS,
    SUM(CASE WHEN UPPER(COALESCE(BASELINE_SOURCE, 'GLOBAL')) = 'TEAM' THEN 1 ELSE 0 END) AS PI_ROWS_SOURCE_TEAM,
    SUM(CASE WHEN UPPER(COALESCE(BASELINE_SOURCE, 'GLOBAL')) = 'PROGRAM' THEN 1 ELSE 0 END) AS PI_ROWS_SOURCE_PROGRAM,
    SUM(CASE WHEN UPPER(COALESCE(BASELINE_SOURCE, 'GLOBAL')) = 'GLOBAL' THEN 1 ELSE 0 END) AS PI_ROWS_SOURCE_GLOBAL
  FROM j
  GROUP BY TEAMID, TEAMNAME
)
SELECT
  @year_from AS YEAR_FROM,
  @year_to AS YEAR_TO,
  @program_name_resolved AS PROGRAM_SCOPE,
  TEAMID,
  TEAMNAME,
  PI_ROWS,
  FEATURE_ROWS,
  CAST(SWAG_POINTS_TOTAL AS DECIMAL(18,2)) AS SWAG_POINTS_TOTAL,
  CAST(DERIVED_FTE_SWAG_TOTAL AS DECIMAL(18,2)) AS DERIVED_FTE_SWAG_TOTAL,
  CAST(DERIVED_FTE_VELOCITY_SNAPSHOT_TOTAL AS DECIMAL(18,2)) AS DERIVED_FTE_VELOCITY_SNAPSHOT_TOTAL,
  CAST(DELTA_VELOCITY_MINUS_SWAG AS DECIMAL(18,2)) AS DELTA_VELOCITY_MINUS_SWAG,
  DISTINCT_BASELINE_VALUES,
  CAST(MIN_BASELINE_POINTS AS DECIMAL(18,2)) AS MIN_BASELINE_POINTS,
  CAST(MAX_BASELINE_POINTS AS DECIMAL(18,2)) AS MAX_BASELINE_POINTS,
  PI_ROWS_SOURCE_TEAM,
  PI_ROWS_SOURCE_PROGRAM,
  PI_ROWS_SOURCE_GLOBAL
FROM team_agg
ORDER BY ABS(DELTA_VELOCITY_MINUS_SWAG) DESC, FEATURE_ROWS DESC, TEAMNAME;
